-- Optional: sample internal transactions table for local testing.
-- Use as INTERNAL_TXN_SOURCE=INTERNAL_TXN_SAMPLE

CREATE TABLE internal_txn_sample (
  int_txn_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  txn_date     DATE NOT NULL,
  amount       NUMBER(18,2) NOT NULL,
  currency     VARCHAR2(10),
  reference    VARCHAR2(200),
  account      VARCHAR2(100)
);

CREATE INDEX ix_int_sample_date ON internal_txn_sample (txn_date);
