-- Core schema for the Automated Multi-Source Financial Reconciliation System (Oracle)

-- ===== Runs / audit =====
CREATE TABLE recon_run (
  run_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_date       DATE NOT NULL,
  source_system  VARCHAR2(50) NOT NULL,
  file_name      VARCHAR2(255),
  file_checksum  VARCHAR2(64),
  status         VARCHAR2(20) NOT NULL,
  started_at     TIMESTAMP,
  ended_at       TIMESTAMP,
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX ix_recon_run_date_src ON recon_run (run_date, source_system);

-- ===== External canonical transactions (loaded from Excel) =====
CREATE TABLE txn_canonical_ext (
  ext_txn_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id           NUMBER NOT NULL REFERENCES recon_run(run_id),
  source_row_num   NUMBER,
  txn_date         DATE NOT NULL,
  amount           NUMBER(18,2) NOT NULL,
  currency         VARCHAR2(10),
  reference        VARCHAR2(200),
  account          VARCHAR2(100),
  narration        VARCHAR2(500),
  counterparty     VARCHAR2(200),
  row_hash         VARCHAR2(64) NOT NULL,
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX ix_ext_run ON txn_canonical_ext (run_id);
CREATE UNIQUE INDEX ux_ext_run_hash ON txn_canonical_ext (run_id, row_hash);

-- ===== Rules (optional extension point; scaffold includes one rule) =====
CREATE TABLE recon_rule (
  rule_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_name       VARCHAR2(100) NOT NULL,
  priority        NUMBER NOT NULL,
  active_flag     CHAR(1) DEFAULT 'Y' NOT NULL,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ===== Matches / breaks =====
CREATE TABLE recon_match (
  match_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id        NUMBER NOT NULL REFERENCES recon_run(run_id),
  rule_id       NUMBER NULL REFERENCES recon_rule(rule_id),
  ext_txn_id    NUMBER NOT NULL REFERENCES txn_canonical_ext(ext_txn_id),
  int_txn_id    NUMBER NOT NULL,
  match_type    VARCHAR2(30) NOT NULL,
  match_score   NUMBER(5,2),
  matched_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX ux_match_run_ext ON recon_match (run_id, ext_txn_id);
CREATE UNIQUE INDEX ux_match_run_int ON recon_match (run_id, int_txn_id);

CREATE TABLE recon_break (
  break_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id        NUMBER NOT NULL REFERENCES recon_run(run_id),
  break_code    VARCHAR2(30) NOT NULL,
  break_reason  VARCHAR2(400),
  ext_txn_id    NUMBER NULL,
  int_txn_id    NUMBER NULL,
  amount        NUMBER(18,2),
  txn_date      DATE,
  reference     VARCHAR2(200),
  account       VARCHAR2(100),
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX ix_break_run_code ON recon_break (run_id, break_code);

-- ===== Metrics for reporting =====
CREATE TABLE recon_metrics (
  run_id            NUMBER PRIMARY KEY REFERENCES recon_run(run_id),
  ext_total_count   NUMBER NOT NULL,
  ext_total_amount  NUMBER(18,2) NOT NULL,
  int_total_count   NUMBER NOT NULL,
  int_total_amount  NUMBER(18,2) NOT NULL,
  matched_count     NUMBER NOT NULL,
  matched_amount    NUMBER(18,2) NOT NULL,
  break_count       NUMBER NOT NULL,
  break_amount      NUMBER(18,2) NOT NULL,
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Seed one default rule (exact 4-key match)
INSERT INTO recon_rule (rule_name, priority, active_flag)
VALUES ('EXACT_REF_AMT_DATE_ACCT', 10, 'Y');

COMMIT;
